runtime bundle/pathogen/autoload/pathogen.vim
execute pathogen#infect()

set wildmode=longest:full,full    " Command-line completion
set ignorecase                    " Case-insensitive searching
set smartcase                     " But case-sensitive if expression contains a capital letter
set hlsearch                      " Highlight matches
set diffopt+=vertical             " Vertical diff splits
set visualbell                    " No beeping
let c_space_errors = 1            " Highlight white space errors
let java_space_errors = 1
let python_space_error_highlight = 1

" Copy/Paste
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
vmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>P "+P
vnoremap y y`]
vnoremap p p`]
nnoremap p p`]

" Grep
nnoremap <Leader>* :Grepper -cword -noprompt -highlight<CR>
nmap gs <plug>(GrepperOperator)
xmap gs <plug>(GrepperOperator)

" Write/Quit
nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>
nnoremap <Leader>x :x<CR>
