runtime bundle/pathogen/autoload/pathogen.vim
execute pathogen#infect()

set wildmode=longest:full,full    " Command-line completion
set ignorecase                    " Case-insensitive searching
set smartcase                     " But case-sensitive if expression contains a capital letter
set hlsearch                      " Highlight matches
set visualbell                    " No beeping
